<?php
$value = array (
  'wwwprefix' => 'http://localhost/zuituware',
  'imgprefix' => 'http://localhost/zuituware',
  'cssprefix' => 'http://localhost/zuituware',
  'sitename' => '测试团购名称',
  'sitetitle' => '我的网站标题',
  'abbreviation' => '测试简称',
  'couponname' => '优惠券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'description' => '',
  'keywords' => '',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'editor' => 'kind',
  'indexteam' => '0',
  'sideteam' => '0',
);
?>